[IV-21-22] Objetivo 6
joaquingv12/car_workshop-maximizer pull request #40
Opened 2021-11-27 12:09 UTC by joaquingv12

Se ha configurado una GitHub Action y CircleCI para la integración continua.

closes #38 
closes #39

2021-11-27 12:31 UTC, joaquingv12 commented
Listo para revisión @JJ.

2021-11-28 11:28 UTC, JJ requested changes
Tampoco hace falta que describas cómo configurar Circle CI más allá de que yo me dé cuenta de que lo has hecho bien.

2021-11-28 11:28 UTC, JJ commented on .github/workflows/test_app.yml
> +        run: pip install invoke
No deberíais instalar invoke, sino poetry y dejar que él maneje las dependencias.

2021-11-28 11:28 UTC, JJ commented on .github/workflows/test_app.yml
> +        run: invoke rundocker
Estás testeando lo mismo en los dos sistemas. No os digo que pongáis dos sistemas porque sí, sino para que testeéis cosas diferentes. Entre otras (y las más importantes) diferentes versiones del lenguaje.

2021-11-29 17:13 UTC, joaquingv12 commented
Ahora poetry es el que se encarga de las dependencias y los distintos sistemas de CI ya no testean lo mismo. 
Listo para revisión @JJ

2021-11-30 11:34 UTC, JJ requested changes
Dale una vuelta más, sobre todo a la justificación de las opciones escogidas en los sistemas de CI.

2021-11-30 11:34 UTC, JJ commented on .circleci/config.yml
> +          command: pyenv global 3.9.7
¿Por qué usas esta versión? ¿Qué tiene de especial?

2021-11-30 11:34 UTC, JJ commented on .github/workflows/test_app.yml
> +on:
¿Por qué ponéis esto? ¿Sólo vais a testear en main? ¿Qué pasa con las ramas?

2021-11-30 11:34 UTC, JJ commented on README.md
> +Con estas opciones, teniendo en cuenta que Travis a pesar de conectarse con GitHub Education te obligaba a elegir un plan e introducir una tarjeta de crédito, he decidido descartarlo. Entre las demás
Y Semaphore CI lo pones y luego te olvidas.

2021-11-30 11:36 UTC, JJ requested changes
Ahora además no usas docker en ningún sitio, y usas los dos sistemas para comprobar versiones de Python, una de ellas random. ¿Podéis por favor tratar de entender por qué hacéis las cosas o por qué se os pide que las hagáis, en vez de limitaros a cambiar valores por aquí y por allí?

2021-11-30 11:46 UTC, joaquingv12 commented
> Ahora además no usas docker en ningún sitio, y usas los dos sistemas para comprobar versiones de Python, una de ellas random. ¿Podéis por favor tratar de entender por qué hacéis las cosas o por qué se os pide que las hagáis, en vez de limitaros a cambiar valores por aquí y por allí?

Creo que se ha confundido, estoy usando docker en CircleCI y además no estoy comprobando las versiones de Python en los dos sistemas.

2021-11-30 11:55 UTC, JJ commented on .circleci/config.yml
> +      - test_app
¿Dónde estás usando Docker aquí?

2021-11-30 12:05 UTC, joaquingv12 commented on .circleci/config.yml
> +      - test_app
En la línea 24, estoy usando la tarea de invoke que corre los test en el contenedor.

2021-11-30 12:18 UTC, JJ commented on .circleci/config.yml
> +      - test_app
Igual convendría que documentárais un poquito las cosas... Pero es cierto que no debería habérseme pasado.

2021-11-30 20:14 UTC, joaquingv12 commented
Listo para revisión @JJ

2021-12-01 08:19 UTC, JJ approved these changes
Sigue sin haber una buena justificación técnica del sistema de CI elegido, pero ya está más o menos aceptable. Para objetivos siguientes, asegúrate de que la justificación de las herramientas está hecha correctamente.

2021-12-01 08:19 UTC, JJ commented on .circleci/config.yml
> +          command: poetry run invoke rundocker
A ver, si vas a instalar poetry solo para ejecutar rundocker no merece mucho la pena, aparte de que es poco visible. También estás instalando una versión de Python arbitraria, cuando ex muy posible que CircleCI ya tenga una versión.

2021-12-01 08:19 UTC, JJ commented on .github/workflows/test_app.yml
> +        os: [ubuntu-latest, macos-latest, windows-latest]
Igual te estás pasando un poco en esto, pero vale...

2021-12-01 11:19 UTC, merged